### ISSUE TITLE
Add an email signup form

### ISSUE THREAD

**Issue by justinjstark** [GirlsCodeLincoln/Website#7]
For parents to get on our email list when we notify when we open applications for new clubs etc. Can be a Google form saving to a Google Sheet or Mailchimp or something else.

**Comment by justinjstark** [comment]
@troynguyen8 @Jasbury2 Any thoughts on where an email-list signup form should go? I have code from MailChimp at [this gist](https://gist.github.com/justinjstark/4bbd363ee95d5bfbb5fa38c9b61a5531)

**Comment by troynguyen8** [comment]
@justinjstark That's hard because we already have a contact form. I envision it as either a link in our nav/footer that says "join our email list" or maybe it could be a checkbox in the contact form that says "join our email list," which afterwards we can make a request to mailchimp's service on the netlify side

**Comment by justinjstark** [comment]
@troynguyen8 Good points. Our email list is the primary way we alert people (along with Facebook) when we open applications for clubs. Maybe we should have a "How do I join" section. If we aren't accepting applications at the time then we have then sign up to the email list to get a notification when we open enrollment.
